### ISSUE TITLE
Missing textures (Chin - Tondenga, Myamsar)

### ISSUE THREAD

**Issue by AimOnEyes** [Lin-zl522/Patapon-3-HD-Texture-Pack#3]
There are missing some textures (tondenga's tail, ears and myamsar's whiskers, ears).

**Comment by Lin-zl522** [comment]
Hi! Could you share the missing textures' hashcodes/files?

**Comment by AimOnEyes** [comment]
![00000000d5882d26fd9a6140](https://github.com/Lin-zl522/Patapon-3-HD-Texture-Pack/assets/121137916/8f3771aa-c3c8-4171-be85-ab45d9a8046a)
![0000000024c286cc013a148d](https://github.com/Lin-zl522/Patapon-3-HD-Texture-Pack/assets/121137916/cda79e7d-17a4-4d59-ae30-2e37d0ecc911)

These two are missing.

**Comment by Lin-zl522** [comment]
Thank you! However, those two textures are in the unit/Patapon folder. The hashcodes are 00000000d5882d26fd9a6140 and 00000000fe1a72461a64a3c6. Can you find them in your local folder?

**Comment by AimOnEyes** [comment]
Yea, but they didn't work. I downloaded the textures to Overhaul and applied them and now everything works fine.

**Comment by AimOnEyes** [comment]
Thanks for the quick replies and help :)
